import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d4e3ff",
        "on-secondary-container": "#5a4100",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "surface-container-lowest": "#060e20",
        primary: "#a4c9ff",
        surface: "#0b1326",
        "secondary-fixed": "#ffdf9f",
        "tertiary-container": "#95a4b9",
        "surface-container-highest": "#2d3449",
        "primary-fixed-dim": "#a4c9ff",
        "on-secondary-fixed": "#261a00",
        outline: "#8b919d",
        "on-primary-fixed": "#001c39",
        "surface-variant": "#2d3449",
        background: "#0b1326",
        "outline-variant": "#414751",
        "on-primary-container": "#003a6b",
        "surface-tint": "#a4c9ff",
        "on-primary": "#00315d",
        "surface-container": "#171f33",
        "primary-container": "#60a5fa",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        error: "#ffb4ab",
        "secondary-container": "#e3aa00",
        "error-container": "#93000a",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#b9c8de",
        "on-secondary": "#402d00",
        tertiary: "#b9c8de",
        "on-primary-fixed-variant": "#004883",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#131b2e",
        "secondary-fixed-dim": "#f9bd22",
        "on-tertiary": "#233143",
        "on-tertiary-fixed": "#0d1c2d",
        "on-tertiary-fixed-variant": "#39485a",
        "on-secondary-fixed-variant": "#5c4300",
        "tertiary-fixed": "#d4e4fa",
        "on-surface-variant": "#c1c7d3",
        "surface-container-high": "#222a3d",
        "on-tertiary-container": "#2c3a4c",
        "inverse-primary": "#0060ac",
        "inverse-surface": "#dae2fd",
        secondary: "#ffc640",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "48px",
        base: "8px",
        gutter: "16px",
        "container-padding-mobile": "20px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "container-padding-desktop": "40px",
      },
      fontFamily: {
        "display-temp": ["var(--font-geist)", "sans-serif"],
        "label-caps": ["var(--font-geist)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-temp": [
          "96px",
          { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
